<?php
    require './controllers/main.php';
?>

<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/custom.css">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="./js/app.js"></script>

    <title>Uoou</title>
  </head>
  <body>
    <div class="container">
      
      <div class="jumbotron">
        <h1 class="display-4">Uoou Solutions Test!</h1>
        <hr class="my-4">
      </div>
      <div class="row">
        
      </div>
      <div class="row">
        <div class="col col-content">
          <table class="table table-hover table-dark mt-1 rounded">
              <thead>
                <tr>
                  <th scope="col">UF</th>
                  <th scope="col">Contaminações</th>
                  <th scope="col">Mortes</th>
                </tr>
              </thead>
              <tbody>
                <?php
                  foreach($data->infectedByRegion as $resultCases) {
                    echo '
                      <tr>
                        <th scope="row">'. $resultCases->state . '</th>
                        <td>'. $resultCases->count . '</td>';
  
                  foreach($data->deceasedByRegion as $resultDies){
                    if ($resultCases->state == $resultDies->state) {
                    echo '<td>' . $resultDies->count . '</td>
                      </tr>';
                      }
                    };
                  };
                ?>
            </table>
        </div>
        <div class="col">
          <div id="top_x_div" class="graph"></div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>